### 
# Get all todolists by user.
GET {{endpoint}}
Authorization: {{accessToken}}

### 
# Get a specific todolist by id.
GET {{endpoint}}/61d6c49e6c46e726d82883ba
Authorization: {{accessToken}}

### 
# Create a todolist.
POST {{endpoint}}
Authorization: {{accessToken}}
Content-Type: application/json

{
  "title": "Kıyafet alışverisi",
  "todos": [
    { "text": "Pantolon" },
    { "text": "Tişört" },
    { "text": "Gömlek" },
    { "text": "Bot" },
    { "text": "Çorap" }
  ]
}

###
# Add a todo to the end of the todo list.
# The parameter is the id of the todolist.
POST {{endpoint}}/61d6c49e6c46e726d82883ba/todo
Authorization: {{accessToken}}
Content-Type: application/json

{
  "text": "sdvasdvads"
}

### 
# Update a todolist by the todolist's id.
# Write only the fields need to be updated.
# These values overwrite previous values.
# If the field is an object or an array, remember to keep its previous values if needed.
PATCH {{endpoint}}/61d6c28b6c46e726d82883b9
Authorization: {{accessToken}}
Content-Type: application/json

{
  "title": "Alışveriş listesi"
}

###
# Update a todo
PATCH {{endpoint}}/61d6c49e6c46e726d82883ba/todo
Authorization: {{accessToken}}
Content-Type: application/json

{
  "todo": {
    "isCompleted": true,
    "_id": "61db49dbcd6c4c2408d1bb3a",
    "text": "selam naber lan"
  }
}

###
# Delete a todolist by the todolist's id.
DELETE {{endpoint}}/61d6c28b6c46e726d82883b9
Authorization: {{accessToken}}

###
# Delete a todo from a todolist.
DELETE {{endpoint}}/61d6c49e6c46e726d82883ba/todo
Authorization: {{accessToken}}
Content-Type: application/json

{
  "todo": {
      "isCompleted": true,
      "_id": "61db49dbcd6c4c2408d1bb3a",
      "text": "selam naber lan"
    }
}

###
@local = http://localhost:3100/api/todolists
@endpoint = {{local}}
@accessToken = {{user1}}

###
# user1 refresh = 61da09f16e023027ecea7fcd
@user1  = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWQ0MmIyMWRlNmViYjIyYThmZmY3ODYiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsImlhdCI6MTY0MTY3OTM0NSwiZXhwIjoxNjQxOTM4NTQ1fQ.DsdUY33vGpTfHiJQmAa0xOyNUDIbVF5LWRsouzHdUl0